### ISSUE TITLE
Traverse is unpredictable in the order darts are returned (making sew! not work right).

### ISSUE THREAD

**Issue by harts12** [goldnd/GeneralizedMaps#2]
I added traverse_test.jl in the tests folder to my pull request. It is a little rudimentary right now, but should get the point across (and I'll improve upon it today).

I create 4 independent ploygons in the same GMap and then call collectcelldarts (which is what sew! uses) for the darts in one 0-cell of each polygon. It prints the index of the darts as it iterates through collectcelldarts.

Two things to notice:
1) The order of the darts traversed is _usually_ the same starting with either dart in the 0-cell. e.g. If dart 1 and dart 8 are in the same 0-cell, interating through collectcelldarts(d1, 0) might return d1 first, then d8, while cellectcelldarts(d8, 0) will also return d1 then d8 instead of d8, d1 as needed for proper sewing. When running the script, you will see sometimes there are exceptions, hence the usually.

2) Running the script repeatedly returns different results.

**Comment by harts12** [comment]
Adding a seenlist of type Array and returning that instead of seen (a Set) seems to have fixed the issue. I added a test that passes in this case and am working on updating it so that it will show the shortcomings when the Set is returned. I think the issue was that the order of iteration of Sets can vary, but I'm working on confirming that. That being said, with the way traverse was written, I'm not sure that a set is actually needed since ! in is checked before any pushes to it are attempted. I'm pushing my current revisions up now and will add to them tomorrow.

**Comment by harts12** [comment]
I just added a case and point example on Set to the issue.

**Comment by harts12** [comment]
Case and point on Set iteration:

``` julia
s = Set()

for x in 0:9
     push!(s, x)
end

for x in s
     println(x)
end

0
4
7
9
2
3
5
8
6
1
```

For another test I pushed an array of strings:

``` julia
letters = ["A", "B", "C", "D", "E"]

for l in letters
     push!(s, l)
end

for l in s
     println(l)
end

B
A
C
D
E
```

So, iteration order is not reliable on Sets.

**Comment by sglyon** [comment]
If you want to use set like functionality  still you should look into the OrderedSet type from the DataStructures.jl package.

**Comment by harts12** [comment]
With how it was written, I don't see anywhere set functionality is actually being used, so I think an array should be fine. If I'm missing something though, the OrderedSet type should work great. Thanks for the lead.

**Comment by goldnd** [comment]
An array is probably ok.  Do you have a fix?  If so do you want to submit a pull request?

**Comment by harts12** [comment]
I'm pretty sure it's already incorporated into my pull request from a few
weeks ago.
